/**
 * Curated Unicode emojis for region text.
 * Only widely supported glyphs (roughly Unicode ≤13) — avoids tofu/missing
 * glyphs from newer emoji-mart catalog entries on iOS Safari / Android.
 */

export type RegionEmojiCategoryId =
  | 'places'
  | 'weather'
  | 'nature'
  | 'transport'
  | 'people'
  | 'activity'
  | 'objects'
  | 'symbols'

export type RegionEmoji = {
  id: string
  native: string
  name: string
  keywords: string[]
  categoryId: RegionEmojiCategoryId
}

export const REGION_EMOJI_CATEGORIES: {
  id: RegionEmojiCategoryId
  label: string
}[] = [
  { id: 'places', label: 'Yerler' },
  { id: 'weather', label: 'Hava' },
  { id: 'nature', label: 'Doğa' },
  { id: 'transport', label: 'Ulaşım' },
  { id: 'people', label: 'Yüzler' },
  { id: 'activity', label: 'Aktivite' },
  { id: 'objects', label: 'Nesneler' },
  { id: 'symbols', label: 'Semboller' },
]

export const REGION_EMOJIS: RegionEmoji[] = [
  // Yerler / şehir
  {
    id: 'round_pushpin',
    native: '📍',
    name: 'Konum iğnesi',
    keywords: ['konum', 'pin', 'bölge', 'map'],
    categoryId: 'places',
  },
  {
    id: 'pushpin',
    native: '📌',
    name: 'Raptiye',
    keywords: ['pin', 'not'],
    categoryId: 'places',
  },
  {
    id: 'world_map',
    native: '🗺️',
    name: 'Harita',
    keywords: ['harita', 'map', 'dünya'],
    categoryId: 'places',
  },
  {
    id: 'compass',
    native: '🧭',
    name: 'Pusula',
    keywords: ['pusula', 'yön'],
    categoryId: 'places',
  },
  {
    id: 'cityscape',
    native: '🏙️',
    name: 'Şehir',
    keywords: ['şehir', 'city', 'kent'],
    categoryId: 'places',
  },
  {
    id: 'city_sunset',
    native: '🌆',
    name: 'Şehir akşamı',
    keywords: ['şehir', 'akşam'],
    categoryId: 'places',
  },
  {
    id: 'city_sunrise',
    native: '🌇',
    name: 'Şehir gün batımı',
    keywords: ['gün batımı', 'şehir'],
    categoryId: 'places',
  },
  {
    id: 'night_with_stars',
    native: '🌃',
    name: 'Gece şehri',
    keywords: ['gece', 'yıldız'],
    categoryId: 'places',
  },
  {
    id: 'bridge_at_night',
    native: '🌉',
    name: 'Köprü',
    keywords: ['köprü', 'gece'],
    categoryId: 'places',
  },
  {
    id: 'house',
    native: '🏠',
    name: 'Ev',
    keywords: ['ev', 'home'],
    categoryId: 'places',
  },
  {
    id: 'house_with_garden',
    native: '🏡',
    name: 'Bahçeli ev',
    keywords: ['ev', 'bahçe'],
    categoryId: 'places',
  },
  {
    id: 'office',
    native: '🏢',
    name: 'Ofis',
    keywords: ['ofis', 'bina'],
    categoryId: 'places',
  },
  {
    id: 'hospital',
    native: '🏥',
    name: 'Hastane',
    keywords: ['hastane'],
    categoryId: 'places',
  },
  {
    id: 'school',
    native: '🏫',
    name: 'Okul',
    keywords: ['okul'],
    categoryId: 'places',
  },
  {
    id: 'convenience_store',
    native: '🏪',
    name: 'Market',
    keywords: ['market', 'dükkan'],
    categoryId: 'places',
  },
  {
    id: 'hotel',
    native: '🏨',
    name: 'Otel',
    keywords: ['otel'],
    categoryId: 'places',
  },
  {
    id: 'classical_building',
    native: '🏛️',
    name: 'Klasik bina',
    keywords: ['müze', 'tarih'],
    categoryId: 'places',
  },
  {
    id: 'church',
    native: '⛪',
    name: 'Kilise',
    keywords: ['kilise'],
    categoryId: 'places',
  },
  {
    id: 'mosque',
    native: '🕌',
    name: 'Cami',
    keywords: ['cami', 'mescit'],
    categoryId: 'places',
  },
  {
    id: 'fountain',
    native: '⛲',
    name: 'Çeşme',
    keywords: ['çeşme', 'park'],
    categoryId: 'places',
  },
  {
    id: 'tent',
    native: '⛺',
    name: 'Çadır',
    keywords: ['kamp', 'çadır'],
    categoryId: 'places',
  },
  {
    id: 'camping',
    native: '🏕️',
    name: 'Kamp',
    keywords: ['kamp'],
    categoryId: 'places',
  },
  {
    id: 'beach_with_umbrella',
    native: '🏖️',
    name: 'Plaj',
    keywords: ['plaj', 'deniz', 'sahil'],
    categoryId: 'places',
  },
  {
    id: 'desert_island',
    native: '🏝️',
    name: 'Ada',
    keywords: ['ada', 'tatil'],
    categoryId: 'places',
  },
  {
    id: 'national_park',
    native: '🏞️',
    name: 'Milli park',
    keywords: ['park', 'doğa'],
    categoryId: 'places',
  },
  {
    id: 'stadium',
    native: '🏟️',
    name: 'Stadyum',
    keywords: ['stadyum', 'maç'],
    categoryId: 'places',
  },
  {
    id: 'ferris_wheel',
    native: '🎡',
    name: 'Dönme dolap',
    keywords: ['eğlence', 'park'],
    categoryId: 'places',
  },
  {
    id: 'roller_coaster',
    native: '🎢',
    name: 'Roller coaster',
    keywords: ['eğlence'],
    categoryId: 'places',
  },
  {
    id: 'flag_tr',
    native: '🇹🇷',
    name: 'Türkiye',
    keywords: ['türkiye', 'bayrak', 'tr'],
    categoryId: 'places',
  },

  // Hava
  {
    id: 'sunny',
    native: '☀️',
    name: 'Güneş',
    keywords: ['güneş', 'sıcak', 'hava'],
    categoryId: 'weather',
  },
  {
    id: 'mostly_sunny',
    native: '🌤️',
    name: 'Az bulutlu',
    keywords: ['hava', 'bulut'],
    categoryId: 'weather',
  },
  {
    id: 'partly_sunny',
    native: '⛅',
    name: 'Parçalı bulutlu',
    keywords: ['hava', 'bulut'],
    categoryId: 'weather',
  },
  {
    id: 'cloud',
    native: '☁️',
    name: 'Bulut',
    keywords: ['bulut'],
    categoryId: 'weather',
  },
  {
    id: 'rain_cloud',
    native: '🌧️',
    name: 'Yağmur',
    keywords: ['yağmur', 'ıslak'],
    categoryId: 'weather',
  },
  {
    id: 'thunder_cloud_and_rain',
    native: '⛈️',
    name: 'Fırtına',
    keywords: ['fırtına', 'şimşek'],
    categoryId: 'weather',
  },
  {
    id: 'snowflake',
    native: '❄️',
    name: 'Kar',
    keywords: ['kar', 'soğuk'],
    categoryId: 'weather',
  },
  {
    id: 'snowman',
    native: '⛄',
    name: 'Kardan adam',
    keywords: ['kar'],
    categoryId: 'weather',
  },
  {
    id: 'fog',
    native: '🌫️',
    name: 'Sis',
    keywords: ['sis'],
    categoryId: 'weather',
  },
  {
    id: 'wind_blowing_face',
    native: '💨',
    name: 'Rüzgar',
    keywords: ['rüzgar'],
    categoryId: 'weather',
  },
  {
    id: 'rainbow',
    native: '🌈',
    name: 'Gökkuşağı',
    keywords: ['gökkuşağı'],
    categoryId: 'weather',
  },
  {
    id: 'umbrella',
    native: '☔',
    name: 'Şemsiye',
    keywords: ['şemsiye', 'yağmur'],
    categoryId: 'weather',
  },
  {
    id: 'high_voltage',
    native: '⚡',
    name: 'Şimşek',
    keywords: ['şimşek', 'enerji'],
    categoryId: 'weather',
  },
  {
    id: 'fire',
    native: '🔥',
    name: 'Ateş',
    keywords: ['ateş', 'sıcak'],
    categoryId: 'weather',
  },
  {
    id: 'droplet',
    native: '💧',
    name: 'Damla',
    keywords: ['su', 'damla'],
    categoryId: 'weather',
  },
  {
    id: 'ocean',
    native: '🌊',
    name: 'Dalga',
    keywords: ['deniz', 'dalga'],
    categoryId: 'weather',
  },

  // Doğa
  {
    id: 'mountain',
    native: '⛰️',
    name: 'Dağ',
    keywords: ['dağ'],
    categoryId: 'nature',
  },
  {
    id: 'snow_capped_mountain',
    native: '🏔️',
    name: 'Karlı dağ',
    keywords: ['dağ', 'kar'],
    categoryId: 'nature',
  },
  {
    id: 'volcano',
    native: '🌋',
    name: 'Volkan',
    keywords: ['volkan'],
    categoryId: 'nature',
  },
  {
    id: 'evergreen_tree',
    native: '🌲',
    name: 'Çam',
    keywords: ['ağaç', 'orman'],
    categoryId: 'nature',
  },
  {
    id: 'deciduous_tree',
    native: '🌳',
    name: 'Ağaç',
    keywords: ['ağaç'],
    categoryId: 'nature',
  },
  {
    id: 'palm_tree',
    native: '🌴',
    name: 'Palmiye',
    keywords: ['palmiye', 'tatil'],
    categoryId: 'nature',
  },
  {
    id: 'cactus',
    native: '🌵',
    name: 'Kaktüs',
    keywords: ['kaktüs', 'çöl'],
    categoryId: 'nature',
  },
  {
    id: 'herb',
    native: '🌿',
    name: 'Yaprak',
    keywords: ['yaprak', 'yeşil'],
    categoryId: 'nature',
  },
  {
    id: 'four_leaf_clover',
    native: '🍀',
    name: 'Yonca',
    keywords: ['şans', 'yonca'],
    categoryId: 'nature',
  },
  {
    id: 'maple_leaf',
    native: '🍁',
    name: 'Akçaağaç yaprağı',
    keywords: ['sonbahar'],
    categoryId: 'nature',
  },
  {
    id: 'cherry_blossom',
    native: '🌸',
    name: 'Kiraz çiçeği',
    keywords: ['çiçek'],
    categoryId: 'nature',
  },
  {
    id: 'sunflower',
    native: '🌻',
    name: 'Ayçiçeği',
    keywords: ['çiçek'],
    categoryId: 'nature',
  },
  {
    id: 'rose',
    native: '🌹',
    name: 'Gül',
    keywords: ['gül', 'çiçek'],
    categoryId: 'nature',
  },
  {
    id: 'tulip',
    native: '🌷',
    name: 'Lale',
    keywords: ['lale', 'çiçek'],
    categoryId: 'nature',
  },
  {
    id: 'dog',
    native: '🐶',
    name: 'Köpek',
    keywords: ['köpek'],
    categoryId: 'nature',
  },
  {
    id: 'cat',
    native: '🐱',
    name: 'Kedi',
    keywords: ['kedi'],
    categoryId: 'nature',
  },
  {
    id: 'bird',
    native: '🐦',
    name: 'Kuş',
    keywords: ['kuş'],
    categoryId: 'nature',
  },
  {
    id: 'butterfly',
    native: '🦋',
    name: 'Kelebek',
    keywords: ['kelebek'],
    categoryId: 'nature',
  },

  // Ulaşım
  {
    id: 'car',
    native: '🚗',
    name: 'Araba',
    keywords: ['araba', 'araç'],
    categoryId: 'transport',
  },
  {
    id: 'taxi',
    native: '🚕',
    name: 'Taksi',
    keywords: ['taksi'],
    categoryId: 'transport',
  },
  {
    id: 'bus',
    native: '🚌',
    name: 'Otobüs',
    keywords: ['otobüs'],
    categoryId: 'transport',
  },
  {
    id: 'minibus',
    native: '🚐',
    name: 'Minibüs',
    keywords: ['minibüs', 'van'],
    categoryId: 'transport',
  },
  {
    id: 'truck',
    native: '🚚',
    name: 'Kamyon',
    keywords: ['kamyon'],
    categoryId: 'transport',
  },
  {
    id: 'police_car',
    native: '🚓',
    name: 'Polis arabası',
    keywords: ['polis'],
    categoryId: 'transport',
  },
  {
    id: 'ambulance',
    native: '🚑',
    name: 'Ambulans',
    keywords: ['ambulans'],
    categoryId: 'transport',
  },
  {
    id: 'fire_engine',
    native: '🚒',
    name: 'İtfaiye',
    keywords: ['itfaiye'],
    categoryId: 'transport',
  },
  {
    id: 'motorcycle',
    native: '🏍️',
    name: 'Motosiklet',
    keywords: ['motor'],
    categoryId: 'transport',
  },
  {
    id: 'bicycle',
    native: '🚲',
    name: 'Bisiklet',
    keywords: ['bisiklet'],
    categoryId: 'transport',
  },
  {
    id: 'scooter',
    native: '🛴',
    name: 'Scooter',
    keywords: ['scooter'],
    categoryId: 'transport',
  },
  {
    id: 'metro',
    native: '🚇',
    name: 'Metro',
    keywords: ['metro', 'ray'],
    categoryId: 'transport',
  },
  {
    id: 'train',
    native: '🚆',
    name: 'Tren',
    keywords: ['tren'],
    categoryId: 'transport',
  },
  {
    id: 'tram',
    native: '🚊',
    name: 'Tramvay',
    keywords: ['tramvay'],
    categoryId: 'transport',
  },
  {
    id: 'airplane',
    native: '✈️',
    name: 'Uçak',
    keywords: ['uçak', 'havalimanı'],
    categoryId: 'transport',
  },
  {
    id: 'helicopter',
    native: '🚁',
    name: 'Helikopter',
    keywords: ['helikopter'],
    categoryId: 'transport',
  },
  {
    id: 'ship',
    native: '🚢',
    name: 'Gemi',
    keywords: ['gemi', 'liman'],
    categoryId: 'transport',
  },
  {
    id: 'ferry',
    native: '⛴️',
    name: 'Feribot',
    keywords: ['feribot', 'vapur'],
    categoryId: 'transport',
  },
  {
    id: 'speedboat',
    native: '🚤',
    name: 'Tekne',
    keywords: ['tekne'],
    categoryId: 'transport',
  },
  {
    id: 'fuelpump',
    native: '⛽',
    name: 'Benzinlik',
    keywords: ['benzin', 'yakıt'],
    categoryId: 'transport',
  },
  {
    id: 'construction',
    native: '🚧',
    name: 'İnşaat',
    keywords: ['inşaat', 'yol'],
    categoryId: 'transport',
  },
  {
    id: 'traffic_light',
    native: '🚦',
    name: 'Trafik ışığı',
    keywords: ['trafik'],
    categoryId: 'transport',
  },

  // Yüzler (eski, yaygın desteklenenler)
  {
    id: 'grinning',
    native: '😀',
    name: 'Gülen yüz',
    keywords: ['mutlu', 'gülümse'],
    categoryId: 'people',
  },
  {
    id: 'smile',
    native: '😄',
    name: 'Gülümseme',
    keywords: ['mutlu'],
    categoryId: 'people',
  },
  {
    id: 'joy',
    native: '😂',
    name: 'Gülme',
    keywords: ['gül', 'komik'],
    categoryId: 'people',
  },
  {
    id: 'wink',
    native: '😉',
    name: 'Göz kırpma',
    keywords: ['göz kırp'],
    categoryId: 'people',
  },
  {
    id: 'blush',
    native: '😊',
    name: 'Utangaç gülümseme',
    keywords: ['mutlu'],
    categoryId: 'people',
  },
  {
    id: 'heart_eyes',
    native: '😍',
    name: 'Kalpli gözler',
    keywords: ['aşk', 'beğeni'],
    categoryId: 'people',
  },
  {
    id: 'thinking_face',
    native: '🤔',
    name: 'Düşünme',
    keywords: ['düşün'],
    categoryId: 'people',
  },
  {
    id: 'neutral_face',
    native: '😐',
    name: 'Nötr',
    keywords: ['nötr'],
    categoryId: 'people',
  },
  {
    id: 'sweat',
    native: '😅',
    name: 'Terli gülümseme',
    keywords: ['yoruldu', 'rahatlama'],
    categoryId: 'people',
  },
  {
    id: 'cry',
    native: '😢',
    name: 'Ağlama',
    keywords: ['üzgün'],
    categoryId: 'people',
  },
  {
    id: 'sob',
    native: '😭',
    name: 'Hıçkıra ağlama',
    keywords: ['üzgün'],
    categoryId: 'people',
  },
  {
    id: 'angry',
    native: '😠',
    name: 'Kızgın',
    keywords: ['kızgın'],
    categoryId: 'people',
  },
  {
    id: 'sunglasses',
    native: '😎',
    name: 'Güneş gözlüğü',
    keywords: ['havalı', 'cool'],
    categoryId: 'people',
  },
  {
    id: 'sleeping',
    native: '😴',
    name: 'Uyuyan',
    keywords: ['uyku'],
    categoryId: 'people',
  },
  {
    id: 'wave',
    native: '👋',
    name: 'El salla',
    keywords: ['merhaba', 'el'],
    categoryId: 'people',
  },
  {
    id: 'thumbsup',
    native: '👍',
    name: 'Beğen',
    keywords: ['ok', 'beğen', 'evet'],
    categoryId: 'people',
  },
  {
    id: 'thumbsdown',
    native: '👎',
    name: 'Beğenme',
    keywords: ['hayır'],
    categoryId: 'people',
  },
  {
    id: 'clap',
    native: '👏',
    name: 'Alkış',
    keywords: ['alkış'],
    categoryId: 'people',
  },
  {
    id: 'raised_hands',
    native: '🙌',
    name: 'Eller yukarı',
    keywords: ['kutlama'],
    categoryId: 'people',
  },
  {
    id: 'muscle',
    native: '💪',
    name: 'Kas',
    keywords: ['güç', 'kuvvet'],
    categoryId: 'people',
  },
  {
    id: 'pray',
    native: '🙏',
    name: 'Rica / teşekkür',
    keywords: ['teşekkür', 'lütfen'],
    categoryId: 'people',
  },
  {
    id: 'ok_hand',
    native: '👌',
    name: 'Tamam',
    keywords: ['ok', 'tamam'],
    categoryId: 'people',
  },
  {
    id: 'victory_hand',
    native: '✌️',
    name: 'Zafer',
    keywords: ['zafer', 'iki'],
    categoryId: 'people',
  },

  // Aktivite
  {
    id: 'soccer',
    native: '⚽',
    name: 'Futbol',
    keywords: ['futbol', 'top'],
    categoryId: 'activity',
  },
  {
    id: 'basketball',
    native: '🏀',
    name: 'Basketbol',
    keywords: ['basket'],
    categoryId: 'activity',
  },
  {
    id: 'tennis',
    native: '🎾',
    name: 'Tenis',
    keywords: ['tenis'],
    categoryId: 'activity',
  },
  {
    id: 'running',
    native: '🏃',
    name: 'Koşu',
    keywords: ['koşu', 'spor'],
    categoryId: 'activity',
  },
  {
    id: 'walking',
    native: '🚶',
    name: 'Yürüyüş',
    keywords: ['yürü'],
    categoryId: 'activity',
  },
  {
    id: 'dart',
    native: '🎯',
    name: 'Hedef',
    keywords: ['hedef', 'odak'],
    categoryId: 'activity',
  },
  {
    id: 'trophy',
    native: '🏆',
    name: 'Kupa',
    keywords: ['kupa', 'zafer'],
    categoryId: 'activity',
  },
  {
    id: 'medal',
    native: '🏅',
    name: 'Madalya',
    keywords: ['madalya'],
    categoryId: 'activity',
  },
  {
    id: 'movie_camera',
    native: '🎥',
    name: 'Kamera',
    keywords: ['kamera', 'çekim'],
    categoryId: 'activity',
  },
  {
    id: 'camera',
    native: '📷',
    name: 'Fotoğraf makinesi',
    keywords: ['foto', 'kamera'],
    categoryId: 'activity',
  },
  {
    id: 'microphone',
    native: '🎤',
    name: 'Mikrofon',
    keywords: ['mikrofon', 'ses'],
    categoryId: 'activity',
  },
  {
    id: 'headphones',
    native: '🎧',
    name: 'Kulaklık',
    keywords: ['müzik'],
    categoryId: 'activity',
  },
  {
    id: 'musical_note',
    native: '🎵',
    name: 'Nota',
    keywords: ['müzik'],
    categoryId: 'activity',
  },
  {
    id: 'art',
    native: '🎨',
    name: 'Sanat',
    keywords: ['sanat', 'palet'],
    categoryId: 'activity',
  },
  {
    id: 'tada',
    native: '🎉',
    name: 'Kutlama',
    keywords: ['parti', 'kutlama'],
    categoryId: 'activity',
  },
  {
    id: 'balloon',
    native: '🎈',
    name: 'Balon',
    keywords: ['balon'],
    categoryId: 'activity',
  },
  {
    id: 'gift',
    native: '🎁',
    name: 'Hediye',
    keywords: ['hediye'],
    categoryId: 'activity',
  },

  // Nesneler
  {
    id: 'memo',
    native: '📝',
    name: 'Not',
    keywords: ['not', 'yazı'],
    categoryId: 'objects',
  },
  {
    id: 'clipboard',
    native: '📋',
    name: 'Pano',
    keywords: ['liste', 'pano'],
    categoryId: 'objects',
  },
  {
    id: 'calendar',
    native: '📅',
    name: 'Takvim',
    keywords: ['takvim', 'tarih'],
    categoryId: 'objects',
  },
  {
    id: 'spiral_calendar',
    native: '🗓️',
    name: 'Ajanda',
    keywords: ['takvim'],
    categoryId: 'objects',
  },
  {
    id: 'alarm_clock',
    native: '⏰',
    name: 'Çalar saat',
    keywords: ['saat', 'alarm'],
    categoryId: 'objects',
  },
  {
    id: 'hourglass',
    native: '⏳',
    name: 'Kum saati',
    keywords: ['süre', 'bekliyor'],
    categoryId: 'objects',
  },
  {
    id: 'bulb',
    native: '💡',
    name: 'Ampul',
    keywords: ['fikir'],
    categoryId: 'objects',
  },
  {
    id: 'mag',
    native: '🔍',
    name: 'Büyüteç',
    keywords: ['ara', 'bul'],
    categoryId: 'objects',
  },
  {
    id: 'key',
    native: '🔑',
    name: 'Anahtar',
    keywords: ['anahtar'],
    categoryId: 'objects',
  },
  {
    id: 'lock',
    native: '🔒',
    name: 'Kilit',
    keywords: ['kilit', 'güvenli'],
    categoryId: 'objects',
  },
  {
    id: 'moneybag',
    native: '💰',
    name: 'Para torbası',
    keywords: ['para'],
    categoryId: 'objects',
  },
  {
    id: 'briefcase',
    native: '💼',
    name: 'Evrak çantası',
    keywords: ['iş', 'ofis'],
    categoryId: 'objects',
  },
  {
    id: 'phone',
    native: '📱',
    name: 'Telefon',
    keywords: ['telefon', 'ara'],
    categoryId: 'objects',
  },
  {
    id: 'email',
    native: '📧',
    name: 'E-posta',
    keywords: ['mail', 'e-posta'],
    categoryId: 'objects',
  },
  {
    id: 'package',
    native: '📦',
    name: 'Kutu',
    keywords: ['paket', 'kargo'],
    categoryId: 'objects',
  },
  {
    id: 'wrench',
    native: '🔧',
    name: 'Anahtar (alet)',
    keywords: ['tamir', 'alet'],
    categoryId: 'objects',
  },
  {
    id: 'hammer',
    native: '🔨',
    name: 'Çekiç',
    keywords: ['tamir'],
    categoryId: 'objects',
  },
  {
    id: 'mega',
    native: '📢',
    name: 'Megafon',
    keywords: ['duyuru'],
    categoryId: 'objects',
  },
  {
    id: 'bell',
    native: '🔔',
    name: 'Zil',
    keywords: ['bildirim'],
    categoryId: 'objects',
  },

  // Semboller
  {
    id: 'white_check_mark',
    native: '✅',
    name: 'Onay',
    keywords: ['ok', 'tamam', 'onay'],
    categoryId: 'symbols',
  },
  {
    id: 'x',
    native: '❌',
    name: 'Çarpı',
    keywords: ['hayır', 'iptal'],
    categoryId: 'symbols',
  },
  {
    id: 'warning',
    native: '⚠️',
    name: 'Uyarı',
    keywords: ['dikkat', 'uyarı'],
    categoryId: 'symbols',
  },
  {
    id: 'no_entry',
    native: '⛔',
    name: 'Giriş yok',
    keywords: ['yasak'],
    categoryId: 'symbols',
  },
  {
    id: 'star',
    native: '⭐',
    name: 'Yıldız',
    keywords: ['yıldız', 'favori'],
    categoryId: 'symbols',
  },
  {
    id: 'sparkles',
    native: '✨',
    name: 'Parıltı',
    keywords: ['yeni', 'parlak'],
    categoryId: 'symbols',
  },
  {
    id: 'heart',
    native: '❤️',
    name: 'Kalp',
    keywords: ['aşk', 'kalp'],
    categoryId: 'symbols',
  },
  {
    id: 'blue_heart',
    native: '💙',
    name: 'Mavi kalp',
    keywords: ['kalp'],
    categoryId: 'symbols',
  },
  {
    id: 'green_heart',
    native: '💚',
    name: 'Yeşil kalp',
    keywords: ['kalp'],
    categoryId: 'symbols',
  },
  {
    id: '100',
    native: '💯',
    name: 'Yüz',
    keywords: ['tam', 'yüz'],
    categoryId: 'symbols',
  },
  {
    id: 'exclamation',
    native: '❗',
    name: 'Ünlem',
    keywords: ['önemli'],
    categoryId: 'symbols',
  },
  {
    id: 'question',
    native: '❓',
    name: 'Soru',
    keywords: ['soru'],
    categoryId: 'symbols',
  },
  {
    id: 'red_circle',
    native: '🔴',
    name: 'Kırmızı daire',
    keywords: ['kırmızı'],
    categoryId: 'symbols',
  },
  {
    id: 'orange_circle',
    native: '🟠',
    name: 'Turuncu daire',
    keywords: ['turuncu'],
    categoryId: 'symbols',
  },
  {
    id: 'yellow_circle',
    native: '🟡',
    name: 'Sarı daire',
    keywords: ['sarı'],
    categoryId: 'symbols',
  },
  {
    id: 'green_circle',
    native: '🟢',
    name: 'Yeşil daire',
    keywords: ['yeşil'],
    categoryId: 'symbols',
  },
  {
    id: 'blue_circle',
    native: '🔵',
    name: 'Mavi daire',
    keywords: ['mavi'],
    categoryId: 'symbols',
  },
  {
    id: 'arrow_up',
    native: '⬆️',
    name: 'Yukarı ok',
    keywords: ['yukarı'],
    categoryId: 'symbols',
  },
  {
    id: 'arrow_down',
    native: '⬇️',
    name: 'Aşağı ok',
    keywords: ['aşağı'],
    categoryId: 'symbols',
  },
  {
    id: 'arrow_right',
    native: '➡️',
    name: 'Sağ ok',
    keywords: ['sağ'],
    categoryId: 'symbols',
  },
  {
    id: 'arrow_left',
    native: '⬅️',
    name: 'Sol ok',
    keywords: ['sol'],
    categoryId: 'symbols',
  },
]
